// Generated by https://quicktype.io

export interface GeoJSON {
  type: string
  name: string
  crs: CRS
  features: Feature[]
}

export interface CRS {
  type: string
  properties: CRSProperties
}

export interface CRSProperties {
  name: string
}

export interface Feature {
  type: string
  properties: FeatureProperties
  geometry: Geometry
}

export interface Geometry {
  type: string
  coordinates: Array<Array<Array<GeoPoint>>>
}

export interface FeatureProperties {
  Entity: string
  Layer: string
  LyrFrzn: number
  LyrOn: number
  Color: number
  Linetype: string
  Elevation: number
  LineWt: number
  RefName: null
  DocUpdate: string
}

export type GeoPoint = [number, number, number]
